version: "3"

services:
  pds:
    image: ghcr.io/bluesky-social/pds:sha-3f0cdfa8441c578eb42eb6e5eadbf909abe9ecfd
    restart: unless-stopped
    environment: 
      - PDS_HOSTNAME=pds.stupid.fish
      - PDS_DATA_DIRECTORY=/pds
      - PDS_BLOBSTORE_DISK_LOCATION=/blobstore
      - PDS_DID_PLC_URL=https://plc.directory
      - PDS_BSKY_APP_VIEW_URL=https://api.bsky.app
      - PDS_BSKY_APP_VIEW_DID=did:web:api.bsky.app
      - PDS_REPORT_SERVICE_URL=https://mod.bsky.app
      - PDS_REPORT_SERVICE_DID=did:plc:ar7c4by46qjdydhdevvrndac
      - PDS_CRAWLERS=https://bsky.network
      - LOG_ENABLED=true
      - PDS_EMAIL_FROM_ADDRESS=alina@tei.su
      - PDS_INVITE_REQUIRED=true
      # forward secret variables
      - PDS_JWT_SECRET=$PDS_JWT_SECRET
      - PDS_ADMIN_PASSWORD=$PDS_ADMIN_PASSWORD
      - PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=$PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
      - PDS_EMAIL_SMTP_URL=$PDS_EMAIL_SMTP_URL
    volumes:
      - type: bind
        source: /srv/bluesky-pds/data
        target: /pds
      - type: bind
        source: /mnt/puffer/bluesky-pds
        target: /blobstore
