option-as-alt = 'left'

[adaptive-theme]
light = "ayu-light"
dark = "ayu-dark"

[cursor]
shape = 'beam'
blinking = true
blinking-interval = 500 

[editor]
program = "micro"
args = []

[window]
width = 800
height = 600

[renderer]
performance = "high"
backend = "automatic"

[fonts]
size = 13

[fonts.regular]
family = "IosevkaSS05 Nerd Font"
style = "Light"

[bindings]
keys = [
  { key = "left", with = "option", bytes = [27, 98] },
  { key = "right", with = "option", bytes = [27, 102] },
  { key = "left", with = "super", bytes = [1] },
  { key = "right", with = "super", bytes = [5] },
  { key = "back", with = "option", bytes = [27, 127] },
  { key = "back", with = "super", bytes = [21] },
  { key = "с", with = "super", action = "Copy"},
  { key = "м", with = "super", action = "Paste"},
  { key = "е", with = "super", action = "CreateTab"},
  { key = "ц", with = "super", action = "CloseTab"},
]

